### PR TITLE
F/712 fix ui bugs

### LINKED ISSUE #712: UI bugs
**Please describe the bug:**  
Unexpectedly occurred after merging with dev. 

- [x] Treemap close button (open detailed view, see close button subheader too small)

- [x] one db margin is off (add just one db, see margin of db color is not symmetric)

- [x] add db window too small for large db names (open databases, add long db name, see that there is no margin between sql field and db name)

- [x] Access Frequency card is bottom left not rounded, why?

- [x] unify close button at remove db

- [x] remove v-list-item-btn 

- [x] SQL Dialoge remove the CLOSE

**What is the expected behavior? Please describe:**  
Everything to look nice. 

**Screenshot(s):**  

**Affected Component(s):**  
`UI`, `frontend`,

### PR DESCRIPTION
**Pull request by monasobh**
# Resolves #712 

**Does your pull request solve a problem? Please describe:**  
Solves small ui bugs like missing margin or not responsive components.

**Does your pull request add a feature? Please describe:**  
This PR fixes small UI bugs. 

**Affected Component(s):**  
`UI`, `Frontend`,

### CODE REVIEW

File: hyrisecockpit/frontend/src/views/AppDrawer.vue [hunk 1]
```diff
@@ -237,4 +237,9 @@ export default defineComponent({
   padding-top: 4px;
   padding-bottom: 4px;
 }
+.settingsbutton {
```
Comment (schTi) [inline hyrisecockpit/frontend/src/views/AppDrawer.vue]: this is not used anywhere, isnt it?

**Review by schTi — CHANGES_REQUESTED** [review]
Thanks for the fixes. I adapt those tests

**Review by schTi — APPROVED** [review]
