### PR TITLE
f/ fix timestamps formatting

### LINKED ISSUE #458: different time locales in frontend
**Please describe the bug:**  
different time formats in frontend

**What is the expected behavior? Please describe:**  
we should use a consistent time locale for `toLocalString` etc. --> encapsulate in function

### PR DESCRIPTION
**Pull request by MaxSchneider1337**
# Resolves #458 and #457 

**Does your pull request solve a problem? Please describe:**  
fixes timestamp locale and formatting

**Affected Component(s):**  
Frontend

### CODE REVIEW

File: hyrisecockpit/frontend/src/components/details/TimeInterval.vue [hunk 1]
```diff
@@ -1,4 +1,4 @@
-<template>
+x<template>
```
Comment (schTi) [inline hyrisecockpit/frontend/src/components/details/TimeInterval.vue]: ???

**Review by schTi — CHANGES_REQUESTED** [review]

File: hyrisecockpit/frontend/src/components/details/TimeInterval.vue (hunk 1 above)
Comment (MaxSchneider1337) [reply hyrisecockpit/frontend/src/components/details/TimeInterval.vue]: wtf

**Review by schTi — APPROVED** [review]
